{{- if .Values.account.name }}
apiVersion: jetstream.nats.io/v1beta2
kind: Account
metadata:
  name: {{ .Values.account.name }}
  labels:
    {{- include "jmap2nats.labels" . | nindent 4 }}
spec:
  name: {{ .Values.account.name | quote }}
  servers:
    {{- with .Values.account.servers }}
    {{- toYaml . | nindent 4 }}
    {{- else }}
    - {{ .Values.config.nats.url | quote }}
    {{- end }}
  user:
    secret:
      name: {{ .Values.account.secretName | default .Values.auth.nats.secretName | default .Values.auth.jmap.secretName | quote }}
    user: {{ .Values.account.userKey | quote }}
    password: {{ .Values.account.passwordKey | default .Values.auth.nats.passwordKey | quote }}
{{- end }}
